[q0202]
name = "Total Capex- civil"
old_name = "210"
Deduced_Data_Type = "Int64"
R_and_D_Type = "210_C"

[q0203]
name = "Total Capex- defence"
old_name = "210"
Deduced_Data_Type = "Int64"
R_and_D_Type = "210_D"

[q0204]
name = "Land acquired- civil"
old_name = "219"
Deduced_Data_Type = "Int64"
R_and_D_Type = "219_C"

[q0205]
name = "Land acquired- defence"
old_name = "219"
Deduced_Data_Type = "Int64"
R_and_D_Type = "219_D"

[q0206]
name = "Buildings- civil"
old_name = "220"
Deduced_Data_Type = "Int64"
R_and_D_Type = "220_C"

[q0207]
name = "Buildings-defence"
old_name = "220"
Deduced_Data_Type = "Int64"
R_and_D_Type = "221_D"

[q0208]
name = "Equipment and machinery- civil"
old_name = "q0208"
Deduced_Data_Type = "Int64"
R_and_D_Type = "q0208_C"

[q0209]
name = "Equipment and machinery- defence"
old_name = "q0208"
Deduced_Data_Type = "Int64"
R_and_D_Type = "q0208_D"

[q0210]
name = "Computer software- civil"
old_name = "221"
Deduced_Data_Type = "Int64"
R_and_D_Type = "221_C"

[q0211]
name = "Computer software- defence"
old_name = "221"
Deduced_Data_Type = "Int64"
R_and_D_Type = "221_D"

[q0212]
name = "Total non-capex- civil"
old_name = "204"
Deduced_Data_Type = "Int64"
R_and_D_Type = "204_C"

[q0213]
name = "Total non-capex- defence"
old_name = "204"
Deduced_Data_Type = "Int64"
R_and_D_Type = "204_D"

[q0214]
name = "Salaries and Wages- civil"
old_name = "202"
Deduced_Data_Type = "Int64"
R_and_D_Type = "202_C"

[q0215]
name = "Salaries and Wages -defence"
old_name = "202"
Deduced_Data_Type = "Int64"
R_and_D_Type = "202_D"

[q0216]
name = "Materials- civil"
old_name = "222"
Deduced_Data_Type = "Int64"
R_and_D_Type = "222_C"

[q0217]
name = "Materials- defence"
old_name = "222"
Deduced_Data_Type = "Int64"
R_and_D_Type = "222_D"

[q0218]
name = "Services- civil"
old_name = "223"
Deduced_Data_Type = "Int64"
R_and_D_Type = "223_C"

[q0219]
name = "Services-defence"
old_name = "223"
Deduced_Data_Type = "Int64"
R_and_D_Type = "223_D"

[q0222]
name = "Total capex and non-capex- civil"
old_name = "211"
Deduced_Data_Type = "Int64"
R_and_D_Type = "211_C"

[q0223]
name = "Total capex and non-capex- defence"
old_name = "211"
Deduced_Data_Type = "Int64"
R_and_D_Type = "211_D"

[q0224]
name = "Basic research- civil"
old_name = "205"
Deduced_Data_Type = "Int64"
R_and_D_Type = "205_C"

[q0225]
name = "Basic research- defence"
old_name = "205"
Deduced_Data_Type = "Int64"
R_and_D_Type = "205_D"

[q0226]
name = "Applied research- civil"
old_name = "206"
Deduced_Data_Type = "Int64"
R_and_D_Type = "206_C"

[q0227]
name = "Applied research- defence"
old_name = "206"
Deduced_Data_Type = "Int64"
R_and_D_Type = "206_D"

[q0228]
name = "Experimental - civil"
old_name = "207"
Deduced_Data_Type = "Int64"
R_and_D_Type = "207_C"

[q0229]
name = "Experimental- defence"
old_name = "207"
Deduced_Data_Type = "Int64"
R_and_D_Type = "207_D"

[q0301]
name = "Own funds- Civil"
old_name = "212"
Deduced_Data_Type = "Int64"
R_and_D_Type = "212_C"

[q0302]
name = "Own funds-defence"
old_name = "212"
Deduced_Data_Type = "Int64"
R_and_D_Type = "212_D"

[q0303]
name = "UK Gov- civil"
old_name = "214"
Deduced_Data_Type = "Int64"
R_and_D_Type = "214_C"

[q0304]
name = "UK Gov- defence"
old_name = "214"
Deduced_Data_Type = "Int64"
R_and_D_Type = "214_D"

[q0305]
name = "Other UK private business- civil"
old_name = "216"
Deduced_Data_Type = "Int64"
R_and_D_Type = "216_C"

[q0306]
name = "Other UK private business- defence"
old_name = "216"
Deduced_Data_Type = "Int64"
R_and_D_Type = "216_D"

[q0307]
name = "UK PNP - Civil"
old_name = "242"
Deduced_Data_Type = "Int64"
R_and_D_Type = "242_C"

[q0308]
name = "UK PNP - defence"
old_name = "242"
Deduced_Data_Type = "Int64"
R_and_D_Type = "242_D"

[q0309]
name = "Business enterprises in group outside uk- civil"
old_name = "243"
Deduced_Data_Type = "Int64"
R_and_D_Type = "243_C"

[q0310]
name = "Business enterprises in group outside uk- defence"
old_name = "243"
Deduced_Data_Type = "Int64"
R_and_D_Type = "243_D"

[q0311]
name = "Other business enterprises outside uk- civil"
old_name = "244"
Deduced_Data_Type = "Int64"
R_and_D_Type = "243_C"

[q0312]
name = "Other business enterprises outside uk- defence"
old_name = "244"
Deduced_Data_Type = "Int64"
R_and_D_Type = "243_D"

[q0313]
name = "Other Governments outside uk- civil"
old_name = "245"
Deduced_Data_Type = "Int64"
R_and_D_Type = "245_C"

[q0314]
name = "Other Governments outside uk- defence"
old_name = "245"
Deduced_Data_Type = "Int64"
R_and_D_Type = "245_D"

[q0315]
name = "Higher education outside uk- civil"
old_name = "246"
Deduced_Data_Type = "Int64"
R_and_D_Type = "246_C"

[q0316]
name = "Higher education outside uk- defence"
old_name = "246"
Deduced_Data_Type = "Int64"
R_and_D_Type = "246_D"

[q0317]
name = "Non-profit outside uk- civil"
old_name = "247"
Deduced_Data_Type = "Int64"
R_and_D_Type = "247_C"

[q0318]
name = "Non-profit outside uk- defence"
old_name = "247"
Deduced_Data_Type = "Int64"
R_and_D_Type = "247_D"

[q0319]
name = "Commission of EU- civil"
old_name = "q0319"
Deduced_Data_Type = "Int64"

[q0320]
name = "Commission of EU- defence"
old_name = "q0320"
Deduced_Data_Type = "Int64"

[q0321]
name = "International organisations- civil"
old_name = "248"
Deduced_Data_Type = "Int64"
R_and_D_Type = "248_C"

[q0322]
name = "International organisations- defence"
old_name = "248"
Deduced_Data_Type = "Int64"
R_and_D_Type = "248_D"

[q0323]
name = "Any other orgs outside uk- civil"
old_name = "q0323"
Deduced_Data_Type = "Int64"

[q0324]
name = "Any other orgs outside uk- defence"
old_name = "q0324"
Deduced_Data_Type = "Int64"

[q0325]
name = "Total funding- civil"
old_name = "218"
Deduced_Data_Type = "Int64"
R_and_D_Type = "218_C"

[q0326]
name = "Total funding- defence"
old_name = "218"
Deduced_Data_Type = "Int64"
R_and_D_Type = "218_D"

[q0327]
name = "UK Research council- civil"
old_name = "214"
Deduced_Data_Type = "Int64"
R_and_D_Type = "214_C"

[q0328]
name = "UK Research council- defence"
old_name = "214"
Deduced_Data_Type = "Int64"
R_and_D_Type = "214_D"

[q0329]
name = "(New) UK Higher Education - civil"
old_name = "250"
Deduced_Data_Type = "Int64"
R_and_D_Type = "250_C"

[q0330]
name = "(New) UK Higher Education - defence"
old_name = "250"
Deduced_Data_Type = "Int64"
R_and_D_Type = "250_D"

[q0501]
name = "Researchers male"
old_name = "headcount_res_m"
Deduced_Data_Type = "Int64"

[q0502]
name = "Researchers female"
old_name = "headcount_res_f"
Deduced_Data_Type = "Int64"

[q0503]
name = "Technicians Male"
old_name = "headcount_tec_m"
Deduced_Data_Type = "Int64"

[q0504]
name = "Technicians female"
old_name = "headcount_tec_f"
Deduced_Data_Type = "Int64"

[q0505]
name = "Others Male"
old_name = "headcount_oth_m"
Deduced_Data_Type = "Int64"

[q0506]
name = "Others female"
old_name = "headcount_oth_f"
Deduced_Data_Type = "Int64"

[q0507]
name = "Total HC Male"
old_name = "headcount_tot_m"
Deduced_Data_Type = "Int64"

[q0508]
name = "headcount_tot_f"
old_name = "508"
Deduced_Data_Type = "Int64"

[q0509]
name = "FTE Researchers- civil"
old_name = "405"
Deduced_Data_Type = "Float"
R_and_D_Type = "405_C"

[q0510]
name = "FTE Researchers- defence"
old_name = "405"
Deduced_Data_Type = "Float"
R_and_D_Type = "405_D"

[q0511]
name = "FTE Technicians- civil"
old_name = "407"
Deduced_Data_Type = "Float"
R_and_D_Type = "407_C"

[q0512]
name = "FTE Technicians- defence"
old_name = "407"
Deduced_Data_Type = "Float"
R_and_D_Type = "407_D"

[q0513]
name = "FTE Others- civil"
old_name = "409"
Deduced_Data_Type = "Float"
R_and_D_Type = "409_C"

[q0514]
name = "FTE Others- defence"
old_name = "409"
Deduced_Data_Type = "Float"
R_and_D_Type = "409_D"

[q0515]
name = "Total FTE- civil"
old_name = "411"
Deduced_Data_Type = "Float"
R_and_D_Type = "411_C"

[q0516]
name = "Total FTE- defence"
old_name = "411"
Deduced_Data_Type = "Float"
R_and_D_Type = "411_D"

[q0601]
name = "Postcode"
old_name = "postcodes_harmonised"
Deduced_Data_Type = "String"

[q0602]
name = "% of R&D"
old_name = "602"
Deduced_Data_Type = "Int64"
